BE: Use environment variables for Django settings

diff --git a/build-prod b/build-prod
--- a/build-prod
+++ b/build-prod
@@ -3,14 +3,20 @@
 # Build project for production
 
 
+## Check if server/.env is setup correctly for production build
+if grep -q "DEBUG=True" server/.env; then
+    echo "ERROR: DEBUG is set to True in server/.env"
+    echo "Please ensure that .env is setup correctly for production build."
+    exit 1
+fi
+
+
 ## Build Backend
 
-manage() {
-	venv/bin/python server/manage.py $@ --settings=config.settings_production
-}
-
-manage migrate
-manage collectstatic --noinput
+source venv/bin/activate
+python server/manage.py migrate
+python server/manage.py collectstatic --noinput
+deactivate
 
 
 ## Build Frontend
